add logrotate

diff --git a/Pack/src/DEBIAN/postinst b/Pack/src/DEBIAN/postinst
--- a/Pack/src/DEBIAN/postinst
+++ b/Pack/src/DEBIAN/postinst
@@ -46,7 +46,7 @@ read_params_debconf()
 #    UPGRADE="$RET"
     db_get r7mdaserver/fqdn-name || true
     printf "Debug: $RET\n"
-    HOSTNAME="${RET:-localhost}"
+    MDA_HOSTNAME="${RET:-localhost}"
 
 	echo "Current parameters:"
     echo "MDA_API_KEY: $MDA_API_KEY"
@@ -58,7 +58,7 @@ read_params_debconf()
     echo "MDA_DB_NAME: $MDA_DB_NAME"
     echo "MDA_DB_USER: $MDA_DB_USER"
     echo "MDA_DB_PWD: $MDA_DB_PWD"
-    echo "HOSTNAME: $HOSTNAME"
+    echo "MDA_HOSTNAME: $MDA_HOSTNAME"
 
 }
 
@@ -118,7 +118,7 @@ conf_cert()
 	sed -i "s#{{ MDA_SSL_CERT }}#$MDA_CERT_FILENAME#g" $MDA_CONF_ENV
 	sed -i "s#{{ MDA_SSL_KEY }}#$MDA_KEY_FILENAME#g" $MDA_CONF_ENV
 	sed -i "s#{{ MDA_DH_KEY }}#$MDA_DH_FILENAME#g" $MDA_CONF_ENV
-	sed -i "s#{{ HOSTNAME }}#$HOSTNAME#g" $MDA_CONF_ENV
+	sed -i "s#{{ MDA_HOSTNAME }}#$MDA_HOSTNAME#g" $MDA_CONF_ENV
 }
 
 conf_db()
@@ -276,3 +276,10 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 fi
 # End automatically added section
 
+
+#Logrotate
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -d /run/systemd/system ]; then
+		deb-systemd-invoke restart 'logrotate.service' >/dev/null || true
+	fi
+fi
